export const FETCH_MY_DASHBOARD_DETAILS = "FETCH_MY_DASHBOARD_DETAILS";
export const ADD_TO_MY_PORTFOLIO = "ADD_TO_MY_PORTFOLIO";
export const SELECTED_STOCK_DETAILS = "SELECTED_STOCK_DETAILS";
export const UPDATE_LIVE_STOCK_DATA = "UPDATE_LIVE_STOCK_DATA";
export const UPDATE_WALLET = "UPDATE_WALLET";